let users = [
    {
        "id": 1,
        "username": "proximate",
        "firstname": "Marco",
        "lastname": "Rensch",
        "password": "fnevenviefjeifnceievnbiregfnioefe",
        "email": "marco.rensch@nx-designs.ch",
        "status": 1,
        "usergroup": 2,
        "created": Date.now().toString(),
    },
    {
        "id": 2,
        "username": "nicole",
        "firstname": "Nicole",
        "lastname": "",
        "password": "fnevenviefjeifnceievnbiregfnioefe",
        "email": "nicole@nx-designs.ch",
        "status": 1,
        "usergroup": 1,
        "created": Date.now().toString(),
    },
    {
        "id": 3,
        "username": "elay",
        "firstname": "Elay",
        "lastname": "Muggwyler",
        "password": "fnevenviefjeifnceievnbiregfnioefe",
        "email": "elay@nx-designs.ch",
        "status": 1,
        "usergroup": 1,
        "created": Date.now().toString(),
    },
    {
        "id": 4,
        "username": "clodos",
        "firstname": "Claudia",
        "lastname": "Martinez",
        "password": "fnevenviefjeifnceievnbiregfnioefe",
        "email": "c@irgendwas-kein-plan.ch",
        "status": 1,
        "usergroup": 2,
        "created": Date.now().toString(),
    },
    {
        "id": 5,
        "username": "foo",
        "firstname": "Foo",
        "lastname": "Bar",
        "password": "fnevenviefjeifnceievnbiregfnioefe",
        "email": "foobi@bar.ch",
        "status": 1,
        "usergroup": 1,
        "created": Date.now().toString(),
    }
];

export default users;

