# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: getong/mariadb-action@v1.1
      with:
        host port: 3800 # Optional, default value is 3306. The port of host
        container port: 3307 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        #mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
        mysql database: 'babylon_test' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'root' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: ${{ secrets.DatabasePassword }} # Required if "mysql user" exists. The password for the "mysql user"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Verify MariaDB connection
      run: |
          while ! mysqladmin ping -h"127.0.0.1" -P3800 --silent; do
            sleep 1
          done          

    - name: Run SQL query
      run: |
        mysql -h 127.0.0.1 -P3800 -u root -proot -e "CREATE DATABASE IF NOT EXISTS babylon_test;"
    - name: Run SQL files to install database tables
      run: |
        for file in sql/*.sql; do
        mysql -h 127.0.0.1 -P3800 -u root -proot-D babylon_test < "$file"
        done
    - name: Install Dependencies
      run: npm install
    - name: Run CI Tests
      run: npm run ci-test
